### ISSUE TITLE
OBC housekeeping uptime not working

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/OBC_FlightSoftware#6]
From XTCE, it seems the OBC uptime is fixed to a random value

![image](https://user-images.githubusercontent.com/19912937/94376316-1a7b5580-011a-11eb-89fb-78647a415bd8.png)

**Comment by CasperBroekhuizen** [comment]
Did you check you forwarded the EGSE for the latest XTCE file. I notice missing fields..

**Comment by StefanoSperetta** [comment]
good point, pull failed and I did not notice it :-(
